services:
  - type: web
    name: irminsul-v2
    env: node
    plan: free
    buildCommand: npm install --production=false
    startCommand: node --import tsx/esm src/index.ts
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=256
